#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-WWW-Form-UrlEncoded
Version  : 0.26
Release  : 9
URL      : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/WWW-Form-UrlEncoded-0.26.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/WWW-Form-UrlEncoded-0.26.tar.gz
Summary  : 'parser and builder for application/x-www-form-urlencoded'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-WWW-Form-UrlEncoded-license = %{version}-%{release}
Requires: perl-WWW-Form-UrlEncoded-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
[![Build Status](https://travis-ci.org/kazeburo/WWW-Form-UrlEncoded.svg?branch=master)](https://travis-ci.org/kazeburo/WWW-Form-UrlEncoded)
# NAME

%package dev
Summary: dev components for the perl-WWW-Form-UrlEncoded package.
Group: Development
Provides: perl-WWW-Form-UrlEncoded-devel = %{version}-%{release}
Requires: perl-WWW-Form-UrlEncoded = %{version}-%{release}

%description dev
dev components for the perl-WWW-Form-UrlEncoded package.


%package license
Summary: license components for the perl-WWW-Form-UrlEncoded package.
Group: Default

%description license
license components for the perl-WWW-Form-UrlEncoded package.


%package perl
Summary: perl components for the perl-WWW-Form-UrlEncoded package.
Group: Default
Requires: perl-WWW-Form-UrlEncoded = %{version}-%{release}

%description perl
perl components for the perl-WWW-Form-UrlEncoded package.


%prep
%setup -q -n WWW-Form-UrlEncoded-0.26
cd %{_builddir}/WWW-Form-UrlEncoded-0.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-WWW-Form-UrlEncoded
cp %{_builddir}/WWW-Form-UrlEncoded-0.26/LICENSE %{buildroot}/usr/share/package-licenses/perl-WWW-Form-UrlEncoded/220fe941787679d8a043c0444548ac186c86f309
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/WWW::Form::UrlEncoded.3
/usr/share/man/man3/WWW::Form::UrlEncoded::PP.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-WWW-Form-UrlEncoded/220fe941787679d8a043c0444548ac186c86f309

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
